name: flutter_app_cc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  webview_flutter: ^4.0.6
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3


  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png
    - assets/background.jpg

    - assets/images/store1.png
    - assets/images/store2.png
    - assets/images/store3.png
    - assets/images/store4.png
    - assets/images/store5.png
    - assets/images/store6.png
    - assets/images/store7.png
    - assets/images/store8.png
    - assets/images/store9.png
    - assets/images/store10.png


    - assets/images/banner.png
    - assets/images/promo1.png
    - assets/images/promo2.png
    - assets/images/promo3.png
    - assets/images/promo4.png
    - assets/images/logo.png


