name: flutter_app_cc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png
    - assets/background.jpg
    - assets/logo.png
    - assets/images/store1.png
    - assets/images/store2.png
    - assets/images/store3.png
    - assets/images/store4.png
    - assets/images/store5.png
    - assets/images/store6.png